# set base image (host OS)
FROM libcalculadora:1.0

# set the working directory in the container
WORKDIR .

EXPOSE 8200

# command to run on container start
CMD [ "node", "src/apps/AppSubtracao.js" ]
