version: "3.2"
   
networks:
  calc_overlay:
    driver: overlay
    attachable: true
   
services:
  libcalculadora:
    build:
      context: .
      dockerfile: Dockerfile-depend
    image: "libcalculadora:1.0"
  calculadora:
    build:
      context: .
      dockerfile: Dockerfile-calculadora
    image: "calculadora:${VERSAO}"
    ports:
      - "8000:8000"
    networks:
      - calc_overlay
    env_file:
      - .env
  soma:
    build:
      context: .
      dockerfile: Dockerfile-soma
    image: "soma:${VERSAO}"
    ports:
      - "8100:8100"
    networks:
      - calc_overlay
    env_file:
      - .env
  subtracao:
    build:
      context: .
      dockerfile: Dockerfile-subtracao
    image: "subtracao:${VERSAO}"
    ports:
      - "8200:8200"
    networks:
      - calc_overlay
    env_file:
      - .env
  multiplicacao:
    build:
      context: .
      dockerfile: Dockerfile-multiplicacao
    image: "multiplicacao:${VERSAO}"
    ports:
      - "8300:8300"
    networks:
      - calc_overlay
    env_file:
      - .env
  divisao:
    build:
      context: .
      dockerfile: Dockerfile-divisao
    image: "divisao:${VERSAO}"
    ports:
      - "8400:8400"
    networks:
      - calc_overlay
    env_file:
      - .env
